services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      TOKEN: ${TOKEN}
    container_name: betty
    restart: unless-stopped